// Generated by Wrangler by running `wrangler types`

interface Env {
	OIDC_ISSUER: "https://oidc.example.com";
	OIDC_CLIENT_ID: "abc123";
	OIDC_REDIRECT_URI: "http://localhost:8787/auth/callback";
	OIDC_CLIENT_SECRET: string;
}
