#:schema node_modules/wrangler/config-schema.json
name = "hono-oidc-example"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]
OIDC_ISSUER = "https://oidc.example.com"
OIDC_CLIENT_ID = "abc123"
OIDC_REDIRECT_URI = "http://localhost:8787/auth/callback"
